
name: bot_dash
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  - altair=4.2.2
  - appnope
  - asttokens
  - attrs=25.3.0
  - blinker=1.9.0
  - cachetools=6.1.0
  - certifi=2025.6.15
  - charset-normalizer=3.4.2
  - click=8.1.7
  - comm
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy
  - decorator
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - exceptiongroup
  - executing
  - faker=37.4.0
  - filelock=3.16.1
  - flask=3.1.1
  - flask-cors=6.0.1
  - fonttools=4.58.5
  - fsspec=2024.9.0
  - gitdb=4.0.12
  - gitpython=3.1.44
  - idna=3.10
  - imageio=2.35.1
  - importlib_metadata
  - ipykernel
  - ipython
  - itsdangerous=2.2.0
  - jedi
  - jinja2=3.1.4
  - joblib=1.4.2
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jupyter_client
  - jupyter_core
  - kiwisolver=1.4.8
  - lazy_loader=0.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.10.3
  - matplotlib-inline
  - mdurl=0.1.2
  - mpmath=1.3.0
  - narwhals=1.45.0
  - nest_asyncio
  - networkx=3.3
  - numpy=2.2.6
  - openpyxl=3.1.5
  - packaging=24.1
  - pandas=2.2.3
  - parso
  - pexpect
  - pickleshare
  - pillow=10.4.0
  - platformdirs
  - plotly=6.2.0
  - prompt_toolkit
  - protobuf=3.20.3
  - psutil
  - ptyprocess
  - pure_eval
  - pyarrow=20.0.0
  - pydeck=0.9.1
  - pygments
  - pympler=1.1
  - pyparsing=3.2.3
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - pyzmq
  - referencing=0.36.2
  - requests=2.32.4
  - retrying=1.4.0
  - rich=14.1.0
  - rpds-py=0.26.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - semver=3.0.4
  - six=1.16.0
  - smmap=5.0.2
  - stack_data
  - tenacity=9.1.2
  - threadpoolctl=3.5.0
  - tifffile=2024.9.20
  - toml=0.10.2
  - toolz=1.0.0
  - tornado
  - tqdm=4.66.5
  - traitlets
  - typing_extensions=4.12.2
  - tzdata=2024.2
  - tzlocal=5.3.1
  - urllib3=2.5.0
  - validators=0.35.0
  - wcwidth
  - werkzeug=3.1.3
  - zipp

  - pip:
    - dash==3.1.1
    - dash-bootstrap-components==2.0.3
    - streamlit==1.47.1
    - streamlit-geolocation==0.0.10
